//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicalHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientMedicalHistory()
        {
            this.MedicalReports = new HashSet<MedicalReport>();
        }
    
        public int DetailID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> BloodPressureMin { get; set; }
        public Nullable<double> BloodPressureMax { get; set; }
        public string Symptoms { get; set; }
        public bool MedicalHistory { get; set; }
        public string MedicalHistoryDetail { get; set; }
        public string Medicine { get; set; }
        public string DoctorComments { get; set; }
        public string RecommendedTests { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalReport> MedicalReports { get; set; }
    }
}
